export const useStyles = MUITheme => ({
  textareaIconContainer: {
    display: "flex",
    alignItems: "flex-start",
  },
  iconTooltipContainer: {
    width: "auto !important",
    position: "relative",
    "& > svg": {
      paddingRight: 8,
      color: MUITheme.palette.text.disabled,
      cursor: "pointer",
      fontSize: 18,
      verticalAlign: "middle",
    },
    "& p": {
      width: 377,
      padding: 16,
      borderRadius: 4,
      display: "none",
      position: "absolute",
      bottom: 9,
      background: MUITheme.palette.text.lightGrey,
      boxShadow: "0 8px 10px 1px rgba(0,0,0,0.14), 0 3px 14px 2px rgba(0,0,0,0.12), 0 5px 5px -3px rgba(0,0,0,0.2)",
      color: MUITheme.palette.text.white,
      fontSize: 16,
      lineHeight: "20px",
      zIndex: 999,
    },
    "&:hover": {
      "& svg": { color: MUITheme.palette.primary.main },
      "& p": { display: "block" },
    },
  },
  textareaContainer: {
    position: "relative",
    "& textarea": {
      boxSizing: "border-box",
      width: "100%",
      padding: 10,
      borderRadius: 4,
      borderColor: "rgba(25,25,25,.32)",
      color: MUITheme.palette.text.darkGrey,
      fontFamily: MUITheme.typography.fontFamily,
      fontSize: 16,
      lineHeight: "20px",
      resize: "none",
      "&:disabled": {
        background: MUITheme.palette.background.white,
        borderColor: MUITheme.palette.border.secondary,
        color: "#999",
      },
      "&:hover": {
        borderColor: `${MUITheme.palette.text.primary} !important`,
      },
      "&:focus": {
        borderWidth: 2,
        borderColor: `${MUITheme.palette.primary.main} !important`,
        outline: "none",
      },
    },
  },
  error: {
    borderWidth: 2,
    borderColor: `${MUITheme.palette.border.alertBox} !important`,
  },
  label: {
    position: "absolute",
    background: MUITheme.palette.background.white,
    top: 0,
    letterSpacing: 0.4,
    lineHeight: "16px",
    fontSize: 12,
    left: 0,
    padding: "0 10px 0 5px",
    color: MUITheme.palette.text.darkGrey,
    transform: "translate(5px, -9px) scale(0.90)",
  },
  charLength: {
    marginBottom: 25,
    display: "block",
    paddingLeft: 14,
    color: MUITheme.palette.text.primary,
    fontFamily: MUITheme.typography.fontFamily,
    fontSize: 12,
    letterSpacing: 0.39,
  },
  extraInfo: {
    marginLeft: 17,
    color: MUITheme.palette.text.primary,
    fontFamily: MUITheme.typography.fontFamily,
    fontSize: 12.17,
    letterSpacing: 0.4,
    lineHeight: "16px",
  },
});
